#pragma once

#include "camera.h"
#include "color.h"
#include "image.h"
#include "material.h"
#include "point_3d.h"
#include "point_light.h"
#include "ray.h"
#include "sampler.h"
#include "scene.h"
#include "scene_loader.h"
#include "sphere.h"
#include "vector_3d.h"
#include "view_plane.h"
